name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Здесь перечисляем все твои папки с проектами
        project-path: [
          'ai-assisted-framework-generation',
          'ai-test-code-generation'
        ]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci
      working-directory: ./${{ matrix.project-path }}

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      working-directory: ./${{ matrix.project-path }}

    - name: Run Playwright tests
      run: npx playwright test
      working-directory: ./${{ matrix.project-path }}

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-${{ matrix.project-path }}
        path: ${{ matrix.project-path }}/playwright-report/
        retention-days: 30